port=8083

[user]
name="kevin"
age=14
sex=1

[database]
servers=["127.0.0.1","127.0.0.2","127.0.0.3"]
connection_max=5000
enabled=true

[servers]
  # 你可以依照你的意愿缩进。使用空格或Tab。TOML不会在意。
  [servers.a]
  ip="34.23.1.4"
  port=6379

  [servers.b]
  ip="34.23.1.6"
  port=9921

#嵌套
[nest]
data=[["n1","n2"],[1,2]]

# 在数组里换行没有关系。
names = [
  "li",
  "wang"
]
